### ISSUE TITLE
[Mobile] ToDo

### ISSUE THREAD

**Issue by hrueger** [hrueger/AGFree#3]
- [x] Autologin
- [x] JWT Token Refresh
- [x] Schedules in modal
- [x] Create groups
- [x] Create account
- [x] Search users
- [x] View user schedules
